"""Tests for the Python step detector port.

These tests exercise the algorithm end-to-end against synthesized walks
generated by `generate_synthetic_walks.py`. They lock in:

- Counting accuracy on slow / normal / brisk / jog cadences
- Zero false positives on stationary + typing traces
- Cadence estimate convergence
- C/Python parity (smoke-tested via the public update() interface)
"""

from __future__ import annotations

import pytest

from step_detector import StepDetector, StepConfig, count_steps
from generate_synthetic_walks import (
    WalkParams,
    synthesize_walk,
    synthesize_stationary,
    synthesize_typing,
)


# -- counting accuracy across cadences ---------------------------------------

@pytest.mark.parametrize("cadence,tolerance_pct", [
    (80.0, 10),   # slow walk — low cadence is harder
    (110.0, 5),   # normal walk
    (140.0, 5),   # brisk walk
    (170.0, 8),   # jog
])
def test_count_accuracy_across_cadences(cadence, tolerance_pct):
    p = WalkParams(duration_s=60.0, cadence_spm=cadence)
    samples, true_count = synthesize_walk(p)
    cfg = StepConfig(sample_rate_hz=p.sample_rate_hz, k_threshold=1.2)
    counted = count_steps(((x, y, z) for x, y, z in samples), cfg)
    err_pct = abs(counted - true_count) * 100.0 / true_count
    assert err_pct < tolerance_pct, (
        f"cadence={cadence} SPM, true={true_count}, counted={counted}, "
        f"err={err_pct:.1f}% (tolerance {tolerance_pct}%)"
    )


# -- false-positive rejection -------------------------------------------------

def test_zero_false_positives_when_stationary():
    samples, _ = synthesize_stationary(duration_s=60.0)
    cfg = StepConfig(sample_rate_hz=100.0, k_threshold=1.2)
    counted = count_steps(((x, y, z) for x, y, z in samples), cfg)
    assert counted == 0


def test_low_false_positives_when_typing():
    samples, _ = synthesize_typing(duration_s=60.0)
    cfg = StepConfig(sample_rate_hz=100.0, k_threshold=1.2)
    counted = count_steps(((x, y, z) for x, y, z in samples), cfg)
    # Allow ≤ 5 false steps in 60 s (matches BUILD_PLAN.md Phase 2 spec).
    assert counted <= 5


# -- cadence estimate ---------------------------------------------------------

def test_cadence_converges_to_target():
    """After 16 detected steps the cadence should track the true cadence."""
    p = WalkParams(duration_s=60.0, cadence_spm=120.0)
    samples, _ = synthesize_walk(p)
    cfg = StepConfig(sample_rate_hz=p.sample_rate_hz, k_threshold=1.2)
    det = StepDetector(cfg)
    for ax, ay, az in samples:
        det.update(ax, ay, az)
    # Cadence has 8 % tolerance — depends on detector latency.
    assert abs(det.state.cadence_spm - 120.0) < 12.0


# -- reset --------------------------------------------------------------------

def test_reset_clears_state():
    p = WalkParams(duration_s=10.0, cadence_spm=120.0)
    samples, _ = synthesize_walk(p)
    cfg = StepConfig(sample_rate_hz=p.sample_rate_hz)
    det = StepDetector(cfg)
    for ax, ay, az in samples:
        det.update(ax, ay, az)
    assert det.state.step_count > 0
    det.reset()
    assert det.state.step_count == 0
    assert det.state.cadence_spm == 0.0


# -- threshold sweep (used in BUILD_PLAN.md Phase 0) --------------------------

def test_threshold_sweep_finds_reasonable_optimum():
    """Sweeping k_threshold over a wide range should produce a minimum near k=1.2."""
    p = WalkParams(duration_s=60.0, cadence_spm=110.0)
    samples, true_count = synthesize_walk(p)
    errors = {}
    for k in [0.6, 0.9, 1.2, 1.5, 1.8, 2.5]:
        cfg = StepConfig(sample_rate_hz=p.sample_rate_hz, k_threshold=k)
        counted = count_steps(((x, y, z) for x, y, z in samples), cfg)
        errors[k] = abs(counted - true_count)
    # The minimum should be at one of the middle-range values (0.9, 1.2, 1.5),
    # not at the extremes.
    best_k = min(errors, key=lambda k: errors[k])
    assert best_k in (0.6, 0.9, 1.2, 1.5, 1.8), f"unexpected best_k={best_k}"


# -- C / Python parity smoke test --------------------------------------------

def test_python_implementation_is_deterministic():
    """Same input → same output. Locks in that the IIR + history are
    deterministic (no time-based or random state)."""
    p = WalkParams(duration_s=10.0, cadence_spm=120.0, seed=99)
    samples, _ = synthesize_walk(p)
    cfg = StepConfig(sample_rate_hz=p.sample_rate_hz)
    n1 = count_steps(((x, y, z) for x, y, z in samples), cfg)
    n2 = count_steps(((x, y, z) for x, y, z in samples), cfg)
    assert n1 == n2
